# Generated by Django 3.2.25 on 2025-04-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='age',
            field=models.TextField(),
        ),
    ]
