# Generated by Django 3.2.25 on 2025-04-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
